"use client";
import { useRef } from "react";
import { BellRing,ChartNoAxesCombined,Gauge,MapPinned,Radar,ShieldCheck,Waypoints } from "lucide-react";
import { motion,useScroll,useSpring,useTransform } from "motion/react";
const caps=[["Geospatial","Map context for every signal.",MapPinned],["Prediction","Probability narrows future locations.",Waypoints],["Risk","Priority emerges through weighted evidence.",Gauge],["Alerts","Live threats interrupt the operating picture.",BellRing],["Analytics","Patterns become measurable intelligence.",ChartNoAxesCombined],["Response","Authorized teams move from insight to action.",ShieldCheck]] as const;
const orbitPositions=[
  {left:"92%",top:"50%"},
  {left:"71%",top:"86.3731%"},
  {left:"29%",top:"86.3731%"},
  {left:"8%",top:"50%"},
  {left:"29%",top:"13.6269%"},
  {left:"71%",top:"13.6269%"},
];
function Focus({cap,index,p}:{cap:(typeof caps)[number];index:number;p:ReturnType<typeof useSpring>}){const at=index/6;const opacity=useTransform(p,[at-.06,at+.02,at+.13,at+.2],[.18,1,1,.18]);const x=useTransform(p,[at-.06,at+.02,at+.2],[-20,0,16]);const Icon=cap[2];return <motion.div style={{opacity,x}} className="flex items-center gap-4 border-l border-slate-200 py-4 pl-5"><span className="grid h-10 w-10 place-items-center rounded-lg bg-blue-50 text-blue-700"><Icon size={18}/></span><div><b className="text-lg text-[#0b1f3a]">{cap[0]}</b><p className="mt-1 max-w-xs text-xs text-slate-500">{cap[1]}</p></div></motion.div>}
export default function Capabilities(){const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start start","end end"]});const p=useSpring(scrollYProgress,{stiffness:90,damping:28});const ring=useTransform(p,[0,1],[0,300]);const coreScale=useTransform(p,[0,.5,1],[.75,1.12,.82]);return <section ref={ref} id="capabilities" className="relative h-[430vh] bg-white"><div className="sticky top-0 h-screen overflow-hidden"><div className="section-shell grid h-full items-center gap-14 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Capability focus</p><div className="mt-7">{caps.map((c,i)=><Focus key={c[0]} cap={c} index={i} p={p}/>)}</div></div><div className="relative aspect-square max-h-[680px] rounded-full bg-slate-50"><motion.div style={{rotate:ring,scale:coreScale}} className="absolute inset-[12%] rounded-full border border-dashed border-blue-300"/><motion.div style={{rotate:useTransform(ring,v=>-v*.45)}} className="absolute inset-[22%] rounded-full border border-slate-200"><span className="absolute left-1/2 top-[-6px] h-3 w-3 rounded-full bg-blue-700"/></motion.div><div className="absolute inset-[31%] grid place-items-center rounded-full border border-slate-200 bg-white shadow-[0_28px_80px_rgba(15,31,58,.14)]"><Radar size={38} className="text-blue-700"/><motion.div style={{scale:useTransform(p,[0,1],[.5,1.8]),opacity:useTransform(p,[0,.5,1],[.1,.45,.12])}} className="absolute inset-5 rounded-full bg-blue-500/20 blur-xl"/></div>{caps.map((c,i)=><div key={c[0]} style={orbitPositions[i]} className="absolute h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-blue-600"/>)}</div></div></div></section>}
