"use client";
import { useRef } from "react";
import { motion,useScroll,useSpring,useTransform } from "motion/react";
import type { MotionValue } from "motion/react";

const events=[[-42,-35],[34,-40],[-28,28],[43,26],[-2,-12],[5,42],[-48,8],[48,-8]];
function ChaosEvent({point,index,p,chaos,hue}:{point:number[];index:number;p:MotionValue<number>;chaos:MotionValue<number>;hue:MotionValue<string>}){const x=useTransform(p,[0,.75],[`${point[0]}vw`,`${point[0]*.16}vw`]);const y=useTransform(p,[0,.75],[`${point[1]}vh`,`${point[1]*.14}vh`]);return <motion.div style={{x,y,backgroundColor:hue}} className="absolute left-1/2 top-1/2 h-2.5 w-2.5 rounded-full shadow-[0_0_0_7px_rgba(29,78,216,.08)]"><motion.span style={{opacity:chaos}} className="absolute left-4 top-0 whitespace-nowrap rounded border border-slate-200 bg-white px-2 py-1 text-[8px] font-bold text-slate-500">{["COMPLAINT","TXN SIGNAL","LOCATION","EVENT"][index%4]}</motion.span></motion.div>}
export default function ProblemSection(){
 const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start start","end end"]});const p=useSpring(scrollYProgress,{stiffness:90,damping:28});
 const chaos=useTransform(p,[0,.52],[1,0]);const structure=useTransform(p,[.28,.72],[0,1]);const path=useTransform(p,[.2,.72],[0,1]);const titleX=useTransform(p,[0,1],["0%","-50%"]);const hue=useTransform(p,[0,1],["#64748b","#1d4ed8"]);
 return <section ref={ref} className="relative h-[300vh] bg-white"><div className="sticky top-0 h-screen overflow-hidden">
  <div className="section-shell grid h-full items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">The intelligence gap</p><div className="mt-8 w-[200%] overflow-hidden"><motion.div style={{x:titleX}} className="flex w-full"><h2 className="w-1/2 text-[clamp(3rem,6vw,6.5rem)] font-semibold leading-[.9] text-slate-400">Reactive<br/>Investigation</h2><h2 className="w-1/2 text-[clamp(3rem,6vw,6.5rem)] font-semibold leading-[.9] text-[#0b1f3a]">Predictive<br/><span className="text-blue-700">Intelligence</span></h2></motion.div></div><div className="mt-10 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{["Reactive","Detect","Analyze","Predict","Act"].map((x,i)=><span key={x} className="flex items-center gap-3"><span>{x}</span>{i<4&&<i className="h-px w-5 bg-slate-300"/>}</span>)}</div></div>
  <div className="relative aspect-square max-h-[650px] overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-50 grid-noise"><motion.svg viewBox="0 0 500 500" className="absolute inset-0 h-full w-full"><motion.path d="M40 84Q155 190 250 250T448 96M70 380Q170 260 250 250T430 394M95 235L250 250L390 220M250 60L250 250L250 440" fill="none" stroke="#1d4ed8" strokeWidth="1.5" strokeDasharray="5 7" style={{pathLength:path,opacity:structure}}/></motion.svg>
  {events.map((point,i)=><ChaosEvent key={i} point={point} index={i} p={p} chaos={chaos} hue={hue}/>)}
  <motion.div style={{opacity:structure,scale:structure}} className="absolute left-1/2 top-1/2 grid h-24 w-24 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border border-blue-200 bg-white shadow-xl"><b className="text-center text-[10px] tracking-wider text-blue-700">PATTERN<br/>DETECTED</b></motion.div></div></div>
  <div className="absolute bottom-0 left-1/2 h-20 w-px bg-gradient-to-b from-blue-600 to-transparent"/></div></section>
}
